version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

networks:
  app-network:
    driver: bridge
